ALTER TABLE `_u_list` ADD `s_managed_artists` INT(3) NOT NULL DEFAULT '0' AFTER `s_transactions`, ADD INDEX (`s_managed_artists`);

INSERT INTO `_u_roles` ( `name`, `comment`, `type`, `def`, `bofAdmin_access`, `access`, `data`, `comparators`, `s_users`) VALUES
('Artist Managers', 'Default `Artist Manager` role', 'artist', 1, '[]', NULL, '{\"artist\":{\"fixed_fee\":0,\"dyna_fee\":30,\"streaming_royalty\":0.001},\"affiliate\":[]}', NULL, 0);

CREATE TABLE IF NOT EXISTS `_c_m_albums` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `code` varchar(150) NOT NULL,
  `title` tinytext NOT NULL,
  `type` varchar(20) NOT NULL,
  `price` float DEFAULT NULL,
  `price_setting` longtext DEFAULT NULL CHECK (json_valid(`price_setting`)),
  `explicit` int(1) DEFAULT 0,
  `description` mediumtext DEFAULT NULL,
  `cover_id` int(7) DEFAULT NULL,
  `bg_id` int(7) DEFAULT NULL,
  `artist_id` int(8) NOT NULL,
  `uploader_id` int(8) DEFAULT NULL,
  `spotify_id` varchar(30) DEFAULT NULL,
  `spotify_cover` text DEFAULT NULL,
  `spotify_popularity` int(3) DEFAULT NULL,
  `s_tracks` int(3) NOT NULL DEFAULT 0,
  `s_tracks_duration` int(6) NOT NULL DEFAULT 0,
  `s_views` int(11) NOT NULL DEFAULT 0,
  `s_views_unique` int(9) NOT NULL DEFAULT 0,
  `s_likes` int(6) NOT NULL DEFAULT 0,
  `s_reposts` int(6) NOT NULL DEFAULT 0,
  `s_comments` int(9) NOT NULL DEFAULT 0,
  `s_sales` int(6) NOT NULL DEFAULT 0,
  `s_shares` int(9) NOT NULL DEFAULT 0,
  `s_popularity` int(3) NOT NULL DEFAULT 0,
  `s_sources_local` int(1) NOT NULL DEFAULT 0,
  `time_play` timestamp NULL DEFAULT NULL,
  `time_spotify` timestamp NULL DEFAULT NULL,
  `time_release` date DEFAULT NULL,
  `time_update` timestamp NULL DEFAULT NULL,
  `time_add` timestamp NOT NULL DEFAULT current_timestamp(),
  `translations` longtext DEFAULT NULL CHECK (json_valid(`translations`)),
  `seo_url` varchar(100) NOT NULL,
  `seo_image` int(7) DEFAULT NULL,
  `seo_data` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `hash` (`hash`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `seo_url` (`seo_url`),
  KEY `type` (`type`),
  KEY `price` (`price`),
  KEY `explicit` (`explicit`),
  KEY `artist_id` (`artist_id`),
  KEY `user_id` (`uploader_id`),
  KEY `spotify_id` (`spotify_id`),
  KEY `s_views` (`s_views`),
  KEY `s_views_unique` (`s_views_unique`),
  KEY `s_likes` (`s_likes`),
  KEY `s_reposts` (`s_reposts`),
  KEY `s_comments` (`s_comments`),
  KEY `s_sales` (`s_sales`),
  KEY `s_shares` (`s_shares`),
  KEY `s_popularity` (`s_popularity`),
  KEY `time_play` (`time_play`),
  KEY `time_release` (`time_release`),
  KEY `time_add` (`time_add`),
  KEY `s_tracks` (`s_tracks`),
  KEY `cover_id` (`cover_id`),
  KEY `bg_id` (`bg_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_albums_relations` (
  `album_id` int(9) NOT NULL,
  `target_id` int(9) NOT NULL,
  `type` varchar(10) NOT NULL,
  `i` int(6) DEFAULT NULL,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`album_id`,`target_id`,`type`),
  KEY `ID1` (`album_id`,`type`),
  KEY `ID2` (`target_id`,`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_artists` (
  `ID` int(9) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `code` varchar(150) NOT NULL,
  `name` text DEFAULT NULL,
  `cover_id` int(7) DEFAULT NULL,
  `bg_id` int(7) DEFAULT NULL,
  `manager_id` int(9) DEFAULT NULL,
  `spotify_id` varchar(36) DEFAULT NULL,
  `spotify_cover` text DEFAULT NULL,
  `spotify_popularity` int(3) DEFAULT NULL,
  `spotify_followers` bigint(20) DEFAULT NULL,
  `bio_name` varchar(200) DEFAULT NULL,
  `bio_country` varchar(100) DEFAULT NULL,
  `bio_city` varchar(100) DEFAULT NULL,
  `bio_content` longtext DEFAULT NULL,
  `bio_birthday` datetime DEFAULT NULL,
  `bio_deathday` datetime DEFAULT NULL,
  `external_addresses` text DEFAULT NULL,
  `s_albums` int(4) NOT NULL DEFAULT 0,
  `s_subscribers` int(7) NOT NULL DEFAULT 0,
  `s_tracks` int(5) NOT NULL DEFAULT 0,
  `s_tracks_as_ft` int(5) NOT NULL DEFAULT 0,
  `s_albums_as_ft` int(4) NOT NULL DEFAULT 0,
  `s_views` int(11) NOT NULL DEFAULT 0,
  `s_views_unique` int(9) NOT NULL DEFAULT 0,
  `s_popularity` int(3) NOT NULL DEFAULT 0,
  `s_managed` int(1) DEFAULT 0,
  `time_play` timestamp NULL DEFAULT NULL,
  `time_release` datetime DEFAULT NULL,
  `time_spotify` timestamp NULL DEFAULT NULL,
  `time_spotify_related` timestamp NULL DEFAULT NULL,
  `time_spotify_albums` timestamp NULL DEFAULT NULL,
  `time_spotify_discography` timestamp NULL DEFAULT NULL,
  `time_spotify_tracks` timestamp NULL DEFAULT NULL,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  `translations` longtext DEFAULT NULL CHECK (json_valid(`translations`)),
  `seo_url` varchar(100) NOT NULL,
  `seo_image` int(7) DEFAULT NULL,
  `seo_data` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `hash` (`hash`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `seo_url` (`seo_url`),
  KEY `spotify_id` (`spotify_id`),
  KEY `spotify_popularity` (`spotify_popularity`),
  KEY `s_views` (`s_views`),
  KEY `s_views_unique` (`s_views_unique`),
  KEY `time_add` (`time_add`),
  KEY `time_release` (`time_release`),
  KEY `time_play` (`time_play`),
  KEY `s_popularity` (`s_popularity`),
  KEY `s_albums` (`s_albums`),
  KEY `s_subscribers` (`s_subscribers`),
  KEY `s_tracks` (`s_tracks`),
  KEY `s_tracks_as_ft` (`s_tracks_as_ft`),
  KEY `s_albums_as_ft` (`s_albums_as_ft`),
  KEY `cover_id` (`cover_id`),
  KEY `bg_id` (`bg_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_artists_relations` (
  `artist_id` int(9) NOT NULL,
  `target_id` int(9) NOT NULL,
  `type` varchar(10) NOT NULL,
  `i` int(3) DEFAULT NULL,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`artist_id`,`target_id`,`type`),
  KEY `ID1` (`artist_id`,`type`),
  KEY `ID2` (`target_id`,`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_cronjobs` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `comment` tinytext DEFAULT NULL,
  `update_interval` float NOT NULL,
  `execution_interval` int(11) NOT NULL DEFAULT 1,
  `item_limit` int(4) NOT NULL DEFAULT 10,
  `dynamic` tinyint(1) NOT NULL DEFAULT 0,
  `object_type` varchar(20) NOT NULL,
  `object_filters` text DEFAULT NULL,
  `api_name` varchar(20) NOT NULL,
  `api_ids` text DEFAULT NULL,
  `cache` mediumtext DEFAULT NULL,
  `data` longtext DEFAULT NULL,
  `time_update` timestamp NULL DEFAULT NULL,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  `active` int(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  KEY `update_interval` (`update_interval`,`time_update`,`active`),
  KEY `execution_interval` (`execution_interval`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_cronjobs_spotify` (
  `cron_id` int(5) NOT NULL,
  `spotify_id` varchar(22) NOT NULL,
  `local_id` int(8) DEFAULT NULL,
  `time_check` timestamp NULL DEFAULT NULL,
  `time_add` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`cron_id`,`spotify_id`),
  KEY `local_id` (`local_id`),
  KEY `time_check` (`time_check`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_events` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `name` varchar(300) NOT NULL,
  `cover_id` int(11) DEFAULT NULL,
  `manager_id` int(11) NOT NULL,
  `price` float DEFAULT NULL,
  `maximum` int(6) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `website` tinytext DEFAULT NULL,
  `s_views` int(11) NOT NULL DEFAULT 0,
  `s_views_unique` int(11) NOT NULL DEFAULT 0,
  `s_sales` int(11) NOT NULL DEFAULT 0,
  `time_add` timestamp NOT NULL DEFAULT current_timestamp(),
  `seo_url` varchar(100) NOT NULL,
  `seo_image` int(11) DEFAULT NULL,
  `seo_data` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `seo_url` (`seo_url`),
  UNIQUE KEY `hash` (`hash`),
  KEY `manager_id` (`manager_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_genres` (
  `ID` int(5) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `code` varchar(100) NOT NULL,
  `parent_id` int(5) DEFAULT NULL,
  `name` varchar(50) NOT NULL,
  `cover_id` int(7) DEFAULT NULL,
  `bg_id` int(7) DEFAULT NULL,
  `s_views` int(11) NOT NULL DEFAULT 0,
  `s_views_unique` int(9) NOT NULL DEFAULT 0,
  `s_tracks` int(11) NOT NULL DEFAULT 0,
  `s_albums` int(9) NOT NULL DEFAULT 0,
  `s_artists` int(9) NOT NULL DEFAULT 0,
  `s_childs` int(5) NOT NULL DEFAULT 0,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  `translations` longtext DEFAULT NULL CHECK (json_valid(`translations`)),
  `seo_url` varchar(100) NOT NULL,
  `seo_image` int(7) DEFAULT NULL,
  `seo_data` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `seo_url` (`seo_url`),
  UNIQUE KEY `hash` (`hash`),
  KEY `code` (`code`),
  KEY `s_views` (`s_views`),
  KEY `s_views_unique` (`s_views_unique`),
  KEY `s_tracks` (`s_tracks`),
  KEY `s_albums` (`s_albums`),
  KEY `s_artists` (`s_artists`),
  KEY `time_add` (`time_add`),
  KEY `cover_id` (`cover_id`),
  KEY `bg_id` (`bg_id`),
  KEY `parent_id` (`parent_id`),
  KEY `s_childs` (`s_childs`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_langs` (
  `ID` int(5) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `code` varchar(100) NOT NULL,
  `name` varchar(50) NOT NULL,
  `cover_id` int(7) DEFAULT NULL,
  `bg_id` int(7) DEFAULT NULL,
  `s_views` int(11) NOT NULL DEFAULT 0,
  `s_views_unique` int(9) NOT NULL DEFAULT 0,
  `s_tracks` int(11) NOT NULL DEFAULT 0,
  `s_albums` int(9) NOT NULL DEFAULT 0,
  `s_artists` int(9) NOT NULL DEFAULT 0,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  `translations` longtext DEFAULT NULL CHECK (json_valid(`translations`)),
  `seo_url` varchar(100) NOT NULL,
  `seo_image` int(7) DEFAULT NULL,
  `seo_data` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `seo_url` (`seo_url`),
  UNIQUE KEY `hash` (`hash`),
  KEY `code` (`code`),
  KEY `s_views` (`s_views`),
  KEY `s_views_unique` (`s_views_unique`),
  KEY `s_tracks` (`s_tracks`),
  KEY `s_albums` (`s_albums`),
  KEY `s_artists` (`s_artists`),
  KEY `time_add` (`time_add`),
  KEY `cover_id` (`cover_id`),
  KEY `bg_id` (`bg_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_tags` (
  `ID` int(5) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `code` varchar(100) NOT NULL,
  `name` varchar(50) NOT NULL,
  `cover_id` int(7) DEFAULT NULL,
  `bg_id` int(7) DEFAULT NULL,
  `s_views` int(11) NOT NULL DEFAULT 0,
  `s_views_unique` int(9) NOT NULL DEFAULT 0,
  `s_tracks` int(11) NOT NULL DEFAULT 0,
  `s_albums` int(9) NOT NULL DEFAULT 0,
  `s_artists` int(9) NOT NULL DEFAULT 0,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  `translations` longtext DEFAULT NULL CHECK (json_valid(`translations`)),
  `seo_url` varchar(100) NOT NULL,
  `seo_image` int(7) DEFAULT NULL,
  `seo_data` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `seo_url` (`seo_url`),
  UNIQUE KEY `hash` (`hash`),
  KEY `code` (`code`),
  KEY `s_views` (`s_views`),
  KEY `s_views_unique` (`s_views_unique`),
  KEY `s_tracks` (`s_tracks`),
  KEY `s_albums` (`s_albums`),
  KEY `s_artists` (`s_artists`),
  KEY `time_add` (`time_add`),
  KEY `cover_id` (`cover_id`),
  KEY `bg_id` (`bg_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_tracks` (
  `ID` int(9) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) NOT NULL,
  `code` varchar(150) NOT NULL,
  `title` tinytext NOT NULL,
  `duration` int(4) DEFAULT NULL,
  `price` float DEFAULT 0,
  `price_setting` longtext DEFAULT NULL CHECK (json_valid(`price_setting`)),
  `explicit` int(1) NOT NULL DEFAULT 0,
  `cover_id` int(7) DEFAULT NULL,
  `bg_id` int(7) DEFAULT NULL,
  `artist_id` int(8) NOT NULL,
  `album_id` int(8) NOT NULL,
  `album_index` int(3) DEFAULT NULL,
  `album_cd` int(2) DEFAULT NULL,
  `album_artist_id` int(8) DEFAULT NULL,
  `album_price` float DEFAULT NULL,
  `uploader_id` int(8) DEFAULT NULL,
  `spotify_id` varchar(36) DEFAULT NULL,
  `spotify_cover` text DEFAULT NULL,
  `spotify_popularity` int(3) DEFAULT NULL,
  `musixmatch_id` int(11) DEFAULT NULL,
  `description` mediumtext DEFAULT NULL,
  `lyrics` longtext DEFAULT NULL,
  `s_views` int(11) NOT NULL DEFAULT 0,
  `s_views_unique` int(9) NOT NULL DEFAULT 0,
  `s_plays` int(11) NOT NULL DEFAULT 0,
  `s_plays_unique` int(9) NOT NULL DEFAULT 0,
  `s_likes` int(6) NOT NULL DEFAULT 0,
  `s_reposts` int(9) NOT NULL DEFAULT 0,
  `s_downloads` int(9) NOT NULL DEFAULT 0,
  `s_downloads_unique` int(9) NOT NULL DEFAULT 0,
  `s_comments` int(9) NOT NULL DEFAULT 0,
  `s_playlists` int(6) NOT NULL DEFAULT 0,
  `s_sales` int(6) NOT NULL DEFAULT 0,
  `s_shares` int(9) NOT NULL DEFAULT 0,
  `s_popularity` int(3) NOT NULL DEFAULT 0,
  `s_sources` int(2) NOT NULL DEFAULT 0,
  `s_sources_local` int(1) NOT NULL DEFAULT 0,
  `s_muse_report` int(6) DEFAULT 0,
  `time_play` timestamp NULL DEFAULT NULL,
  `time_release` datetime DEFAULT NULL,
  `time_spotify` timestamp NULL DEFAULT NULL,
  `time_musixmatch` timestamp NULL DEFAULT NULL,
  `time_update` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  `translations` longtext DEFAULT NULL CHECK (json_valid(`translations`)),
  `seo_url` varchar(100) NOT NULL,
  `seo_image` int(7) DEFAULT NULL,
  `seo_data` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `hash` (`hash`),
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `seo_url` (`seo_url`),
  KEY `price` (`price`),
  KEY `explicit` (`explicit`),
  KEY `artist_id` (`artist_id`),
  KEY `album_id` (`album_id`),
  KEY `album_artist_id` (`album_artist_id`),
  KEY `user_id` (`uploader_id`),
  KEY `spotify_id` (`spotify_id`),
  KEY `spotify_popularity` (`spotify_popularity`),
  KEY `s_views` (`s_views`),
  KEY `s_views_unique` (`s_views_unique`),
  KEY `s_plays` (`s_plays`),
  KEY `time_add` (`time_add`),
  KEY `time_release` (`time_release`),
  KEY `time_play` (`time_play`),
  KEY `s_sources_local` (`s_sources_local`),
  KEY `s_sources` (`s_sources`),
  KEY `s_plays_unique` (`s_plays_unique`),
  KEY `s_likes` (`s_likes`),
  KEY `s_reposts` (`s_reposts`),
  KEY `s_downloads` (`s_downloads`),
  KEY `s_dowloads_unique` (`s_downloads_unique`),
  KEY `s_comments` (`s_comments`),
  KEY `s_playlists` (`s_playlists`),
  KEY `s_sales` (`s_sales`),
  KEY `s_shares` (`s_shares`),
  KEY `s_popularity` (`s_popularity`),
  KEY `time_spotify` (`time_spotify`),
  KEY `cover_id` (`cover_id`),
  KEY `bg_id` (`bg_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_tracks_relations` (
  `track_id` int(9) NOT NULL,
  `target_id` int(9) NOT NULL,
  `type` varchar(10) NOT NULL,
  `i` int(4) DEFAULT NULL,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`track_id`,`target_id`,`type`),
  KEY `ID1` (`track_id`,`type`),
  KEY `ID2` (`target_id`,`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE IF NOT EXISTS `_c_m_tracks_sources` (
  `ID` int(9) NOT NULL AUTO_INCREMENT,
  `hash` varchar(32) DEFAULT NULL,
  `target_id` int(9) NOT NULL,
  `type` varchar(10) NOT NULL,
  `title` tinytext DEFAULT NULL,
  `download_able` int(1) DEFAULT NULL,
  `stream_able` int(1) DEFAULT NULL,
  `encrypted` int(1) DEFAULT NULL,
  `duration` float DEFAULT NULL,
  `quality` int(1) DEFAULT NULL,
  `data` mediumtext NOT NULL,
  `force_free` int(1) NOT NULL DEFAULT 0,
  `protected` int(1) NOT NULL DEFAULT 0,
  `queue` int(1) NOT NULL DEFAULT 0,
  `queue_old` int(11) DEFAULT NULL,
  `time_add` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `hash` (`hash`),
  KEY `track_id` (`target_id`),
  KEY `type` (`type`),
  KEY `track_id_2` (`target_id`,`type`),
  KEY `quality` (`quality`),
  KEY `force_free` (`force_free`),
  KEY `queue` (`queue`),
  KEY `download_able` (`download_able`),
  KEY `stream_able` (`stream_able`),
  KEY `protected` (`protected`),
  KEY `encrypted` (`encrypted`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `_c_m_genres_hiearchy` (
  `genre_id` int(5) NOT NULL,
  `hook_id` int(5) NOT NULL,
  PRIMARY KEY (`genre_id`,`hook_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

ALTER TABLE `_c_m_tracks` ADD FULLTEXT (`title`);
ALTER TABLE `_c_m_albums` ADD FULLTEXT (`title`);
ALTER TABLE `_c_m_artists` ADD FULLTEXT (`name`);
